
default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  encoding: unicode
  host: localhost
  username: dev
  password: eduardowander
  url: 

development:
  <<: *default
  database: ecommerce_wander_development

test:
  <<: *default
  database: ecommerce_wander_test

production:
  <<: *default
  database: ecommerce_wander_production
